### ISSUE TITLE
Is it possible to add a path truncate option?

### ISSUE THREAD

**Issue by SolidRhino** [speed47/btrfs-list#15]
I have a path from docker: `/var/lib/docker/btrfs/subvolumes/66281c586c95bc969e46ea749970d5d6f77a63a8c8fafec2580e5cc41486df34`
That path is very large, because of that the table is not properly arranged in the terminal.

**Comment by speed47** [comment]
Yes, it was actually somewhere in my mental backlog ;) 
btrfs-backed docker subvols can indeed have very long names!
I'll implement it soon and use this issue to track progression.

**Comment by speed47** [comment]
Just implemented it in the "maxnamelen" branch, you might try it if you like:
https://raw.githubusercontent.com/speed47/btrfs-list/maxnamelen/btrfs-list
There are two new options, `--max-name-len` and `--indent`

**Comment by speed47** [comment]
Released in v2.2, please reopen if it doesn't work as expected!
