### ISSUE TITLE
alignment broken

### ISSUE THREAD

**Issue by freakout42** [speed47/btrfs-list#19]
indented snaps last 4 columns are not aligned correctly 2 spaces offset

    NAME                          TYPE    REFER     EXCL  MOUNTPOINT
    dalivgdab9                      fs       -     4.87G (raid1, 818.28G/825.18G free, 99.16%)
        [main]                 mainvol   16.00k   16.00k /vgd
        adm                     subvol   32.00k   16.00k
            snaps/adm-2023-02-11  rosnap   32.00k   16.00k
        iso                     subvol    2.69G   16.00k
            snaps/iso-2023-02-11  rosnap    2.69G   16.00k
        jail/don                subvol    2.29G    2.29G
        snaps/jail-2023-02-11   rosnap   16.00k   16.00k

![btrfs-list](https://user-images.githubusercontent.com/3446978/218311923-c4b1ead2-3bec-4614-bda0-d85a7c5ea4a8.jpg)

**Comment by speed47** [comment]
I can't seem to be able to reproduce your issue on my side:

![snapbtrfs](https://user-images.githubusercontent.com/218502/221291897-7046c7b0-77f4-4bdf-aa50-b4d8b854b6ac.png)

This might be an issue with your terminal and color codes, do you also have this problem with `--no-color`?

**Comment by freakout42** [comment]
I'm on a standard clean install of Centos7 and use putty 0.73 from a Windows10 machine :

<pre>
dali:~/adm# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

dali:~/adm# echo $TERM
putty

dali:~/adm# echo $LANG
C

dali:~/adm# btrfs-list-2.2/btrfs-list --no-color
NAME                           TYPE    REFER     EXCL  MOUNTPOINT
dalivgd                          fs       -    38.83G (raid1, 370.75G/410.59G free, 90.30%)
    [main]                  mainvol   16.00k   16.00k /vgd
    adm                      subvol  224.00k   16.00k
        snaps/adm-2023-02-18  rosnap  224.00k   16.00k
        snaps/adm-2023-02-19  rosnap  224.00k   16.00k
        snaps/adm-2023-02-20  rosnap  224.00k   16.00k
        snaps/adm-2023-02-21  rosnap  224.00k   16.00k
        snaps/adm-2023-02-22  rosnap  224.00k   16.00k
        snaps/adm-2023-02-23  rosnap  224.00k   16.00k
        snaps/adm-2023-02-24  rosnap  224.00k   16.00k
        snaps/adm-2023-02-25  rosnap  224.00k   16.00k
    iso                      subvol    2.69G   16.00k
        snaps/iso-2023-02-18  rosnap    2.69G   16.00k
        snaps/iso-2023-02-19  rosnap    2.69G   16.00k
        snaps/iso-2023-02-20  rosnap    2.69G   16.00k
        snaps/iso-2023-02-21  rosnap    2.69G   16.00k
        snaps/iso-2023-02-22  rosnap    2.69G   16.00k
        snaps/iso-2023-02-23  rosnap    2.69G   16.00k
        snaps/iso-2023-02-24  rosnap    2.69G   16.00k
        snaps/iso-2023-02-25  rosnap    2.69G   16.00k
    jail/scar                subvol    2.53G   12.86M
        snaps/scar-2023-02-18  rosnap    2.32G   25.22M
        snaps/scar-2023-02-19  rosnap    2.33G    4.54M
        snaps/scar-2023-02-20  rosnap    2.36G    4.56M
        snaps/scar-2023-02-21  rosnap    2.39G    4.59M
        snaps/scar-2023-02-22  rosnap    2.42G    4.61M
        snaps/scar-2023-02-23  rosnap    2.45G    4.61M
        snaps/scar-2023-02-24  rosnap    2.49G    4.63M
        snaps/scar-2023-02-25  rosnap    2.52G  292.00k
    jail/glen                subvol    8.09G   16.00k
        snaps/glen-2023-02-18  rosnap    8.09G   16.00k
        snaps/glen-2023-02-19  rosnap    8.09G   16.00k
        snaps/glen-2023-02-20  rosnap    8.09G   16.00k
        snaps/glen-2023-02-21  rosnap    8.09G   16.00k
        snaps/glen-2023-02-22  rosnap    8.09G   16.00k
        snaps/glen-2023-02-23  rosnap    8.09G   16.00k
        snaps/glen-2023-02-24  rosnap    8.09G   16.00k
        snaps/glen-2023-02-25  rosnap    8.09G   16.00k
    jail/pie2                subvol   14.96G   16.00k
        snaps/pie2-2023-02-18  rosnap   14.96G   16.00k
        snaps/pie2-2023-02-19  rosnap   14.96G   16.00k
        snaps/pie2-2023-02-20  rosnap   14.96G   16.00k
        snaps/pie2-2023-02-21  rosnap   14.96G   16.00k
        snaps/pie2-2023-02-22  rosnap   14.96G   16.00k
        snaps/pie2-2023-02-23  rosnap   14.96G   16.00k
        snaps/pie2-2023-02-24  rosnap   14.96G   16.00k
        snaps/pie2-2023-02-25  rosnap   14.96G   16.00k
    jail/more                subvol    7.85G   16.00k
        snaps/more-2023-02-18  rosnap    7.85G   16.00k
        snaps/more-2023-02-19  rosnap    7.85G   16.00k
        snaps/more-2023-02-20  rosnap    7.85G   16.00k
        snaps/more-2023-02-21  rosnap    7.85G   16.00k
        snaps/more-2023-02-22  rosnap    7.85G   16.00k
        snaps/more-2023-02-23  rosnap    7.85G   16.00k
        snaps/more-2023-02-24  rosnap    7.85G   16.00k
        snaps/more-2023-02-25  rosnap    7.85G   16.00k
    jail/hmm                 subvol  970.21M  183.62M
        snaps/hmm-2023-02-18  rosnap  582.22M   16.00k
        snaps/hmm-2023-02-19  rosnap  582.22M   16.00k
        snaps/hmm-2023-02-20  rosnap  582.22M   16.00k
        snaps/hmm-2023-02-21  rosnap  582.22M   16.00k
        snaps/hmm-2023-02-22  rosnap  582.22M   16.00k
        snaps/hmm-2023-02-23  rosnap  582.22M   16.00k
        snaps/hmm-2023-02-24  rosnap  846.77M  196.00k
        snaps/hmm-2023-02-25  rosnap  846.83M  196.00k
    jail/conf                subvol   16.00k   16.00k
        snaps/conf-2023-02-18  rosnap   16.00k   16.00k
        snaps/conf-2023-02-19  rosnap   16.00k   16.00k
        snaps/conf-2023-02-20  rosnap   16.00k   16.00k
        snaps/conf-2023-02-21  rosnap   16.00k   16.00k
        snaps/conf-2023-02-22  rosnap   16.00k   16.00k
        snaps/conf-2023-02-23  rosnap   16.00k   16.00k
        snaps/conf-2023-02-24  rosnap   16.00k   16.00k
        snaps/conf-2023-02-25  rosnap   16.00k   16.00k
    jail/much                subvol    2.10G    9.06M
        snaps/much-2023-02-21  rosnap    2.06G   10.04M
        snaps/much-2023-02-22  rosnap    2.07G    9.73M
        snaps/much-2023-02-23  rosnap    2.08G   10.30M
        snaps/much-2023-02-24  rosnap    2.09G   10.17M
        snaps/much-2023-02-25  rosnap    2.10G    8.32M
</pre>

**Comment by iameru** [comment]
First of: Thanks for your tool. when using `-s` it is really useful for me!
When including snapshots though..
Maybe this belongs here.
heavily using btrbk to backup and snapshot. currently at 670 subvolumes.
see image for a part of the output
![2023-09-24-161504_1867x992_scrot](https://github.com/speed47/btrfs-list/assets/46875386/459b9d77-0713-4dc3-82a7-6ac5a1ceb416)
