### ISSUE TITLE
Insecure $ENV{ENV} while running with -T switch at /usr/share/perl5/IPC/Open3.pm line 281.

### ISSUE THREAD

**Issue by jorti** [speed47/btrfs-list#3]
Doesn't work in Fedora 29:

```
Insecure $ENV{ENV} while running with -T switch at /usr/share/perl5/IPC/Open3.pm line 281.
```

**Comment by speed47** [comment]
Thanks for your report. The `-T` switch is mainly useful while developing, to ensure the inputs are properly sanitized.
If this causes problems under some systems, removing it then, I'll keep it only while developing.
